[build]

    publish = "dist"

    environment = { NODE_VERSION = "16" }

    command = "npm run test:coverage && bash <(curl -Ls https://coverage.codacy.com/get.sh) report -r coverage/lcov.info && npm run build:netlify"

[dev]

    publish = "dist"

    command = "npm run dev"
