[build]

    publish = "dist"

    # Runs in root directory so traversing to this program is fine
    command = "python3 build/UpdateData.py ${PodId} ${PodKey} ${AirtableKey}; yarn build; node build/tweet_new_episode.js -c ${Twitter_CK} -s ${Twitter_CS} -a ${Twitter_AK} -t ${Twitter_AS}"

[dev]

    publish = "dist"

    # We have a static file in place to help us out so we don't really need
    # to install python to run debug/develop. But if we need it, install
    # python in the enviornment and uncomment this command
    # command = "python3 build/UpdateData.py ${PodId} ${PodKey} ${AirtableKey};"
