[build]

    publish = "dist"

    command = "yarn build:prod"
    # ADD TO END when framework switch is completed: node build/tweet-new-episode.js -c ${Twitter_CK} -s ${Twitter_CS} -a ${Twitter_AK} -t ${Twitter_AS}

[dev]

    publish = "dist"
    #command = "node -p process.env"
    command = "yarn build:dev"
