[build]

    publish = "dist"

    environment = { NODE_VERSION = "20" }

    command = "npm run test:coverage && bash <(curl -Ls https://coverage.codacy.com/get.sh) report -l TypeScript -r coverage/clover.xml && npm run build"

[dev]

    publish = "dist"

    command = "npm run dev"
