backend:
  name: git-gateway
  branch: Version2
publish mode: editorial_workflow
media_folder: "Audio"
collections:
  - name: "Database"
    label: "Database Files"
    create: false
    delete: false
    extension: json
    format: json
    editor:
     preview: false
    files:
      - label: "Episode Data"
        name: "title"
        file: "Database/data.json"
        fields:
          name: title
          label: Title
          widget: string

          



