backend:
  name: git-gateway
  branch: Version2
publish mode: editorial_workflow
media_folder: "Audio"
    create: false
    delete: false 
collections:
  - name: "Database"
    label: "Database Files"
    create: false
    delete: false  
    editor:
     preview: false
    files:
      - label: "Episodes"
        name: "Episodes Name"
        file: "Database/data.json"
        fields:
          - {label: title, name: title, widget: string}


