backend:
  name: git-gateway
  branch: Version2
publish mode: editorial_workflow
media_library: "Audio"
collections:
  - name: "Episode"
    label: "Episode"
    create: false
    extension: json
    files: "Database"
      - label: "Episodes"
        name: "Episodes Name"
        file: "Database/data.json"
        fields:
          - {label: Name, name: episode, widget: string}


