backend:
  name: git-gateway
  branch: Version2
publish mode: editorial_workflow
media_folder: "Audio"
collections:
  - name: "Database"
    label: "Database Files"
    create: false
    delete: false
    extension: json
    editor:
     preview: false
    files:
      - label: "Episode Data"
        name: "episode_data"
        file: "Database/data.json"
        fields:
          - label: "Episodes"
            name: episodes
            widget: list
            fields:
              - label: Episode
                name: "title"
                default: "Not Found"



