backend:
  name: git-gateway
  branch: Version2
publish mode: editorial_workflow
media_folder: "Audio"
collections:
  - name: "Database"
    label: "Database Files"
    create: true
    delete: false  
    editor:
     preview: false
    files:
      - label: "Episode Data"
        name: "episode_data"
        file: "Database/data.json"
        fields:
          - {label: title, name: title, widget: string}


