export default interface IRankingInfo {
    "Episode": string,
    "Game": string,
    "Platform": string,
    "K. Gameplay": number,
    "K. Visuals": number,
    "K. Audio": number,
    "K. Content": number,
    "P. Gameplay": number,
    "P. Visuals": number,
    "P. Audio": number,
    "P. Content": number,
    "Episode Number": number,
    "G. Gameplay": number,
    "G. Visuals": number,
    "G. Audio": number,
    "G. Content": number,
    "IGN": number,
    "Metacritic": number,
    "Year": number,
    "IG Score": number,
    "Kevin's Rating": number,
    "Peter's Rating": number,
    "Guest Rating": number,
    "K. Aesthetics": number,
    "P. Aesthetics": number,
    "G. Aesthetics": number,
    "Gameplay": number,
    "Aesthetics": number,
    "Visuals": number,
    "Audio": number,
    "Content": number,
    "rank": number
}